services:
  postgres:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: canteen
      POSTGRES_PASSWORD: canteen
      POSTGRES_DB: canteen
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
